version: '3.9'

services:

    db:
        build: ./db
        container_name: database
        ports: 
            - "3306:3306"
        volumes:
            - db:/var/lib/mysql
        networks:
            - OS

    samba:
        tty: true
        build: ./samba
        container_name: samba
        ports:
            - "137:137/udp"
            - "138:138/udp"
            - "139:139"
            - "445:445"
        volumes:
            - samba:/home/shareRecord
        networks:
            - OS

volumes:
    db:
    samba:

networks:
    OS:
        driver: bridge

    
