version: '3.9'

services:

    db:
        build: ./db
        container_name: database
        ports: 
            - "3306:3306"
        volumes:
            - db:/var/lib/mysql
        networks:
            OS:
                ipv4_address: 192.168.1.3

    samba:
        tty: true
        build: ./samba
        container_name: samba
        ports:
            - "137:137/udp"
            - "138:138/udp"
            - "139:139"
            - "445:445"
        volumes:
            - /mnt/shareRecord:/mnt/shareRecord
        restart: always
        networks:
            - OS

    dns:
        build: ./dns
        container_name: dns
        ports:
            - "53:53/tcp"
            - "53:53/udp"
        restart: always
        networks:
            OS:
                ipv4_address: 192.168.1.8

    web:
        build: ./web
        container_name: web
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/www/html:/var/www/wordpress
            - /etc/pki/tls/certs:/etc/pki/tls/certs
            - /etc/ssl/certs:/etc/ssl/certs
        networks:
            OS:
                ipv4_address: 192.168.1.4
        dns:
            - 192.168.1.8
        extra_hosts:
            - "pwe69:192.168.1.4"
            - "pwe69.com:192.168.1.4"
        depends_on:
            - db
            - dns

    mail:
        build: ./mail
        container_name: mail
        ports:
            - "25:25"
            - "110:110"
            - "143:143"
            - "465:465"
            - "587:587"
            - "993:993"
            - "995:995"
        volumes:
            - /var/mail:/var/mail
        extra_hosts:
            - "pwe69.pwe69.com:192.168.1.5"
        dns:
            - 192.168.1.8
        networks:
            OS:
                ipv4_address: 192.168.1.5

volumes:
    db:

networks:
    OS:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.1.0/24

    
