version: '3.9'

services:

    db:
        build: ./db
        container_name: database
        ports: 
            - "3306:3306"
        volumes:
            - db:/var/lib/mysql
        networks:
            - OS

    samba:
        tty: true
        build: ./samba
        container_name: samba
        ports:
            - "137:137/udp"
            - "138:138/udp"
            - "139:139"
            - "445:445"
        volumes:
            - /mnt/shareRecord:/mnt/shareRecord
        restart: always
        networks:
            - OS

    dns:
        build: ./dns
        container_name: dns
        ports:
            - "53:53/tcp"
            - "53:53/udp"
        restart: always
        networks:
            OS:
                ipv4_address: 192.168.1.8

volumes:
    db:

networks:
    OS:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.1.0/24

    
