version: '3.9'

services:

    db:
        build: ./db
        container_name: database
        ports: 
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - server-net

    network:
        server-net:
            driver: bridge

    
