version: '3.9'

services:

    db:
        build: ./db
        container_name: database
        ports: 
            - "3306:3306"
        volumes:
            - db:/var/lib/mysql
        networks:
            - OS

volumes:
    db:

networks:
    OS:
        driver: bridge

    
